branches:
  only: 
    - master
language: php
sudo: false
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
before_install: "composer install"
script: "cd test && phpunit UnitTests.php && phpunit OAuthTests.php"
